name: standalone build

on:
  workflow_call:
    inputs:
      runner:
        description: "image to run the build on"
        required: true
        type: string
      target:
        description: "mac/win/linux"
        required: true
        type: string
      branch:
        description: "branch to check out all repos at"
        required: true
        type: string
      build_version:
        description: "override for package.log version"
        required: false
        type: string
      apple_cert:
        description: "apple developer certificate"
        required: false
        type: string
      apple_pass:
        description: "password for apple developer certificate"
        required: false
        type: string
jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: checkout cables_dev
      uses: actions/checkout@v4
      with:
        repository: "undev-studio/cables_dev"
        ref: ${{ inputs.branch }}
        token: ${{ secrets.standalone_token }}
    - name: checkout cables
      uses: actions/checkout@v4
      with:
        repository: "pandrr/cables"
        ref: ${{ inputs.branch }}
        token: ${{ secrets.standalone_token }}
        path: "cables/"
    - name: checkout extensions
      uses: actions/checkout@v4
      with:
        repository: "undev-studio/cables_extensionops"
        ref: "main"
        token: ${{ secrets.standalone_token }}
        path: "cables/src/ops/extensions"
    - name: checkout cables ui
      uses: actions/checkout@v4
      with:
        repository: "undev-studio/cables_ui"
        ref: ${{ inputs.branch }}
        token: ${{ secrets.standalone_token }}
        path: "cables_ui/"
    - name: checkout cables standalone
      uses: actions/checkout@v4
      with:
        path: "cables_electron/"
    - name: install nodejs
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        check-latest: false
    - name: get node path
      shell: bash
      id: local_node
      run: |
        echo "NODE_EXE=$(which node)" >> $GITHUB_OUTPUT
        echo "NPM_EXE=$(which npm)" >> $GITHUB_OUTPUT
    - name: build standalone
      shell: bash
      run: ./hook_standalone.sh ${{ inputs.target }}
      env:
        BUILD_VERSION: ${{ inputs.build_version }}
        GH_TOKEN: ${{ secrets.github_token }}
        CSC_LINK: "${{ inputs.apple_cert }}"
        CSC_KEY_PASSWORD: "${{ inputs.apple_pass }}"
        NODE_EXE: ${{ steps.local_node.outputs.NODE_EXE }}
        NPM_EXE: ${{ steps.local_node.outputs.NPM_EXE }}
