name: dev build

on:
  workflow_dispatch:
 # schedule:
 #   - cron: "0 3 * * *"

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.run_number }}-dev"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}-dev
          draft: true
          prerelease: true
  linux:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ github.run_number }}-dev
      exe_name: cables-${{ github.run_number }}-dev
      tag_name: ${{ github.run_number }}-dev
    secrets: inherit
  # win:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     runner: macos-14
  #     target: win
  #     branch: develop
  #     build_version: ${{ github.run_number }}-dev
  #     exe_name: cables-${{ github.run_number }}-dev
  #     tag_name: ${{ github.run_number }}-dev
  #   secrets: inherit
  # mac:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     runner: macos-14
  #     target: mac
  #     branch: develop
  #     build_version: ${{ github.run_number }}-dev
  #     exe_name: cables-${{ github.run_number }}-dev
  #     tag_name: ${{ github.run_number }}-dev
  #     sign: true
  #     notarize: true
  #   secrets: inherit
