name: dev build

on:
  workflow_dispatch:
 # schedule:
 #   - cron: "0 3 * * *"

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.run_number }}-dev"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: dev-${{ github.run_number }}
          draft: true
          prerelease: true
  #linux:
  #  uses: ./.github/workflows/build.yml
  #  with:
  #    runner: ubuntu-latest
  #    target: linux
  #    branch: develop
  #    build_version: dev-${{ github.run_number }}
  #    exe_name: cables-dev-${{ github.run_number }}-linux
  #    tag_name: dev-${{ github.run_number }}
  #  secrets: inherit
  #win:
  #  uses: ./.github/workflows/build.yml
  #  with:
  #    runner: windows-latest
  #    target: win
  #    branch: develop
  #    build_version: dev-${{ github.run_number }}
  #    exe_name: dev-cables-${{ github.run_number }}-win
  #    tag_name: dev-${{ github.run_number }}
  #  secrets: inherit
  mac:
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: dev-${{ github.run_number }}
      exe_name: cables-dev-${{ github.run_number }}-mac
      tag_name: dev-${{ github.run_number }}
      sign: true
      notarize: true
    secrets: inherit
