name: check gitinfo

on:
  workflow_dispatch:
 # schedule:
 #   - cron: "0 3 * * *"

jobs:
  repoinfos:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cables
        uses: actions/checkout@v4
        with:
          repository: "pandrr/cables"
          ref: "develop"
          token: ${{ secrets.standalone_token }}
          path: "cables/"
      - name: info cables
        shell: bash
        run: |
            cd cables/
            ls -la
            ls -la .git/objects/
            ls -la .git/objects/pack/
            for i in `ls .git/*.pack`; do mv -f $i .git/objects/pack/*.pack; done
            for i in `ls .git/*.pack`; do cat $i | git unpack-objects -r; done

