name: nightly build

on:
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.date.outputs.date }}-nightly"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.date.outputs.date }}-nightly
          draft: false
          prerelease: true
      -   name: set upload url variable
          run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV
  linux:
    needs: draft_release
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ needs.draft_release.outputs.date }}-nightly
      exe_name: cables-${{ needs.draft_release.outputs.date }}-nightly
      tag_name: ${{ needs.draft_release.outputs.date }}-nightly
      upload_url: ${{ env.UPLOAD_URL }}
      release_type: "prerelease"
    secrets: inherit
  win:
    needs: draft_release
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      target: win
      branch: develop
      build_version: ${{ needs.draft_release.outputs.date }}-nightly
      exe_name: cables-${{ needs.draft_release.outputs.date }}-nightly
      tag_name: ${{ needs.draft_release.outputs.date }}-nightly
      upload_url: ${{ env.UPLOAD_URL }}
      release_type: "prerelease"
    secrets: inherit
  mac:
    needs: draft_release
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-latest
      target: mac
      branch: develop
      build_version: ${{ needs.draft_release.outputs.date }}-nightly
      exe_name: cables-${{ needs.draft_release.outputs.date }}-nightly
      tag_name: ${{ needs.draft_release.outputs.date }}-nightly
      upload_url: ${{ env.UPLOAD_URL }}
      release_type: "prerelease"
      sign: true
      notarize: true
    secrets: inherit

