name: nightly dev build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

env:
  releaseName: ${{ github.run_number }}-dev

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: checkout cables_dev
        uses: actions/checkout@v4
        with:
          repository: "undev-studio/cables_dev"
          ref: "master"
          token: ${{ SECRETS.STANDALONE_TOKEN }}
      - name: checkout cables
        uses: actions/checkout@v4
        with:
          repository: "pandrr/cables"
          ref: "develop"
          token: ${{ SECRETS.STANDALONE_TOKEN }}
          path: "cables/"
      - name: checkout cables ui
        uses: actions/checkout@v4
        with:
          repository: "undev-studio/cables_ui"
          ref: "develop"
          token: ${{ SECRETS.STANDALONE_TOKEN }}
          path: "cables_ui/"
      - name: checkout cables standalone
        uses: actions/checkout@v4
        with:
          path: "cables_electron/"
      - name: install python
        uses: actions/setup-python@v5
      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=`cat .nvmrc`" >> $GITHUB_OUTPUT
      - name: install nodejs
        uses: dcodeIO/setup-node-nvm@master
        with:
            node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.releaseName }}
          release_name: ${{ env.releaseName }}
          draft: true
          prerelease: true
      - name: build standalone
        run: ./hook_standalone.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_VERSION: ${{ env.releaseName }}
