name: nightly build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          export DATE=$(date +'%Y-%m-%d')
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.DATE }}-nightly"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.DATE }}-nightly
          draft: false
          prerelease: true
      - name: current date
        run: |
          echo "debug one: "$DATE
          echo "debug two: "$(date +'%Y-%m-%d')
  debug:
    needs: draft_release
    runs-on: ubuntu-latest
    steps:
      - name: current date
        run: |
          echo "debug one: "$DATE
          echo "debug two: "$(date +'%Y-%m-%d')
