name: nightly dev build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

env:
  releaseTag: ${{ github.run_number }}-dev

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: "build: ${{ env.releaseTag }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.releaseTag }}
          draft: true
          prerelease: true
  build_linux:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ github.run_number }}-dev
    secrets: inherit
  build_win:
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      target: win
      branch: develop
      build_version: ${{ github.run_number }}-dev
    secrets: inherit
  build_mac:
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: ${{ github.run_number }}-dev
      sign: true
    secrets: inherit
