name: nightly dev build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

env:
  releaseName: nightly-${{ github.run_id }}.${{ github.run_number }}

jobs:
  mac:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cables_dev
        uses: actions/checkout@v4
        with:
          repository: "undev-studio/cables_dev"
          ref: "master"
          token: ${{ SECRETS.STANDALONE_TOKEN }}
      - name: checkout cables
        uses: actions/checkout@v4
        with:
          repository: "pandrr/cables"
          ref: "develop"
          token: ${{ SECRETS.STANDALONE_TOKEN }}
          path: "cables/"
      - name: checkout cables ui
        uses: actions/checkout@v4
        with:
          repository: "undev-studio/cables_ui"
          ref: "develop"
          token: ${{ SECRETS.STANDALONE_TOKEN }}
          path: "cables_ui/"
      - name: checkout cables standalone
        uses: actions/checkout@v4
        with:
          path: "cables_electron/"
      - name: install nodejs
        uses: actions/setup-node@v1
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: install dependencies
        run: npm install
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.releaseName }}
          release_name: ${{ env.releaseName }}
          draft: true
          prerelease: true
      - name: build standalone
        run: ./hook_standalone.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: files
        run: ls cables_electron/dist/
