name: nightly build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          export DATE=$(date +'%Y-%m-%d')
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.date.outputs.DATE }}-nightly"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.date.outputs.DATE }}-nightly
          draft: false
          prerelease: true
  linux:
    needs: draft_release
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: linux
      branch: develop
      build_version: ${{ needs.draft_release.steps.date.outputs.DATE }}-nightly
      exe_name: cables-${{ needs.draft_release.steps.date.outputs.DATE }}-nightly
      tag_name: v${{ needs.draft_release.steps.date.outputs.DATE }}
    secrets: inherit
  win:
    needs: draft_release
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: win
      branch: develop
      build_version: ${{ needs.draft_release.steps.date.outputs.DATE }}-nightly
      exe_name: cables-${{ needs.draft_release.steps.date.outputs.DATE }}-nightly
      tag_name: v${{ needs.draft_release.steps.date.outputs.DATE }}
    secrets: inherit
  mac:
    needs: draft_release
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: ${{ needs.draft_release.steps.date.outputs.DATE }}-nightly
      exe_name: cables-${{ needs.draft_release.steps.date.outputs.DATE }}-nightly
      tag_name: v${{ needs.draft_release.steps.date.outputs.DATE }}
      sign: true
      notarize: true
    secrets: inherit
