name: release build

on:
  workflow_dispatch:

env:
  releaseTag: ${{ github.run_number }}-dev

jobs:
  build_linux:
    if: false
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ env.releaseTag }}
    secrets: inherit
  build_win:
    if: false
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      target: win
      branch: develop
      build_version: ${{ env.releaseTag }}
    secrets: inherit
  build_mac:
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: ${{ env.releaseTag }}
      apple_cert: "${{ secrets.APPLE_CERT }}"
      apple_pass: "${{ secrets.APPLE_CERT_PASS }}"
    secrets: inherit
