name: release build

on:
  workflow_dispatch:

jobs:
  build_linux:
    if: false
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ github.run_number }}-dev
    secrets: inherit
  build_win:
    if: false
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      target: win
      branch: develop
      build_version: ${{ github.run_number }}-dev
    secrets: inherit
  build_mac:
    if: false
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: ${{ github.run_number }}-dev
      apple_cert: "${{ secrets.APPLE_CERT }}"
      apple_pass: "${{ secrets.APPLE_CERT_PASS }}"
    secrets: inherit
