name: release build

on:
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "build: ${{ env.releaseTag }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.run_number }}-dev
          draft: true
          prerelease: true
  linux:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ github.run_number }}-rc
    secrets: inherit
  win:
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      target: win
      branch: develop
      build_version: ${{ github.run_number }}-rc
    secrets: inherit
  mac:
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: ${{ github.run_number }}-rc
      sign: true
    secrets: inherit
