name: release build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "!v*-dev"

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.releaseTag }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.releaseTag }}
          draft: true
          prerelease: true
  linux:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ env.releaseTag }}
    secrets: inherit
  win:
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      target: win
      branch: develop
      build_version: ${{ env.releaseTag }}
      exe_name: cables-${{ env.releaseTag }}
      tag_name: ${{ env.releaseTag }}
    secrets: inherit
  mac:
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: ${{ env.releaseTag }}
      exe_name: cables-${{ env.releaseTag }}
      tag_name: ${{ env.releaseTag }}
      sign: true
      notarize: true
    secrets: inherit
