name: release build

on:
  workflow_dispatch:

jobs:
  build_linux:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ github.run_number }}-rc
    secrets: inherit
  build_win:
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      target: win
      branch: develop
      build_version: ${{ github.run_number }}-rc
    secrets: inherit
  build_mac:
    uses: ./.github/workflows/build.yml
    with:
      runner: macos-14
      target: mac
      branch: develop
      build_version: ${{ github.run_number }}-rc
      sign: true
    secrets: inherit
