name: release build

on:
  workflow_dispatch:

jobs:
  build_linux:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      target: linux
      branch: develop
      build_version: ${{ github.run_number }}-dev
    secrets: inherit
